import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';

const base = process.env.ACADEMY_AUDIT_URL || 'http://127.0.0.1:3217';
assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname), 'Audit only runs against an isolated local server');
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({viewport:{width:1366,height:900}});
const login = await context.request.post(`${base}/api/auth/login`, {data:{username:process.env.AUDIT_USERNAME || 'audit',password:process.env.AUDIT_PASSWORD || 'local-audit-only'}});
assert.equal(login.status(),200);
const page = await context.newPage();
const folderName=`QA folder ${Date.now()}`;
const errors=[];
page.setDefaultTimeout(15000);
page.on('pageerror', e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});
page.on('requestfailed',r=>console.log('REQUESTFAILED',r.url(),r.failure()));
page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text())});
const writable={threadId:8,name:'Market Events',canSendMessages:true,availabilityStatus:'available'};
const groups=[
 {id:'-100101',title:'QA Academy',isForum:true,canSendMessages:true,topics:[writable,{threadId:10,name:'Market Analysis',canSendMessages:true,availabilityStatus:'available'}]},
 {id:'-100102',title:'QA Empty Forum',isForum:true,canSendMessages:true,topics:[],topicStatusError:'Topic discovery unavailable'},
 {id:'-100104',title:'QA Restricted',isForum:true,canSendMessages:false,publishUnavailableReason:'official_identity_unavailable',topics:[]},
 {id:'-100103',title:'QA Channel',isForum:false,canSendMessages:true,topics:[]}
];
await page.route('**/api/telegram/user-authorization',r=>r.fulfill({json:{ok:true,accounts:[{userId:'101',firstName:'QA',username:'qa_local'},{userId:'202',firstName:'Second',username:'qa_second'}]}}));
await page.route('**/api/group-config',r=>r.fulfill({json:{ok:true,groups:[]}}));
await page.route('**/api/telegram/dialogs?*',r=>r.fulfill({json:{ok:true,groups:new URL(r.request().url()).searchParams.get('userId')==='101'?groups:[]}}));
await page.goto(`${base}/composer`);
console.log('URL',page.url());
await page.getByText('QA Academy',{exact:true}).waitFor();
await mkdir('docs/qa',{recursive:true});
await page.getByText('QA Restricted',{exact:true}).click();
await page.getByText('当前账号无法使用群身份发布，请检查管理员及 Send As 权限。',{exact:true}).waitFor();
assert.equal(await page.locator('details').filter({hasText:'QA Restricted'}).getByRole('checkbox').count(),0);
await page.getByText('QA Empty Forum',{exact:true}).click();
const empty=page.locator('details').filter({hasText:'QA Empty Forum'});
const writableFallback=await empty.getByRole('checkbox').isEnabled().catch(()=>false);
console.log(JSON.stringify({case:'empty-forum-must-not-offer-main-destination',writableFallback,errors}));
await page.setViewportSize({width:390,height:844});
const overflow=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,clipped:[...document.querySelectorAll('main input,main button,main textarea')].filter(e=>e.getBoundingClientRect().right>innerWidth).map(e=>({tag:e.tagName,text:(e.textContent||e.placeholder||'').slice(0,80),right:e.getBoundingClientRect().right}))}));
console.log(JSON.stringify({case:'composer-mobile',...overflow}));
await page.setViewportSize({width:1366,height:900});
await page.getByText('QA Academy',{exact:true}).click();
await page.getByRole('checkbox',{name:'Market Events',exact:false}).check();
await page.getByRole('checkbox',{name:'Market Analysis',exact:false}).check();
await page.getByPlaceholder('例如：每日市场资讯').fill(folderName);
await page.getByRole('button',{name:'保存当前选择',exact:true}).click();
await page.getByText(`已保存发布文件夹“${folderName}”`,{exact:true}).waitFor();
await page.reload();
await page.getByText('QA Academy',{exact:true}).waitFor();
await page.getByRole('button',{name:`${folderName} 2 个目标`,exact:true}).click();
await page.locator('details').filter({hasText:'QA Restricted'}).locator('summary').click();
await page.screenshot({path:'docs/qa/composer-fixed.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'docs/qa/composer-mobile-fixed.png',fullPage:true});
await page.setViewportSize({width:1366,height:900});
await page.getByPlaceholder('请输入消息内容...').fill('QA isolated draft');
const sent=[];
await page.route('**/api/composer/send',async route=>{
  const request=route.request();
  const data=await new Response(request.postDataBuffer(),{headers:{'content-type':request.headers()['content-type']}}).formData();
  sent.push(data.getAll('targets'));
  await route.fulfill({status:207,json:{ok:false,partial:true,error:'部分目标发送失败（成功 1 个，失败 1 个）',results:[{target:'-100101:8'}],errors:[{target:'-100101:10',error:'test failure'}]}});
});
await page.getByRole('button',{name:'立即发送',exact:true}).click();
await page.getByRole('alert').filter({hasText:'部分目标发送失败'}).waitFor();
const retrySelection=await page.locator('input[type=checkbox]:checked').count();
console.log(JSON.stringify({case:'partial-send-retains-only-failed-target',retrySelection,sent}));
await page.getByRole('combobox').selectOption('202');
await page.getByText('当前账号暂无可发言目标',{exact:true}).waitFor();
assert.equal(await page.locator('input[type=checkbox]:checked').count(),0);
await page.getByRole('button',{name:'Switch to English'}).filter({visible:true}).click();
assert.equal(await page.getByRole('combobox').inputValue(),'202','Language change must preserve account');
await page.route('**/api/composer/target-folders',route=>route.fulfill({status:503,json:{ok:false,error:'QA storage unavailable'}}));
await page.reload();
await page.getByRole('alert').filter({hasText:'QA storage unavailable'}).waitFor();
assert.ok(await page.getByText('QA Academy',{exact:true}).isVisible(),'Folder failure must not hide usable targets');
await page.unroute('**/api/composer/target-folders');
await page.getByRole('button',{name:'Reload',exact:true}).click();
await page.getByText(folderName,{exact:true}).waitFor();
const stored=await (await context.request.get(`${base}/api/composer/target-folders`)).json();
const savedFolder=stored.folders.find(folder=>folder.name===folderName);
assert.deepEqual(savedFolder.targets.map(target=>target.id),['-100101:8','-100101:10']);
await context.request.post(`${base}/api/composer/target-folders`,{data:{action:'delete',id:savedFolder.id}});
console.log(JSON.stringify({case:'folder-persistence-account-switch-load-retry',ok:true}));
await browser.close();
assert.equal(retrySelection,1,'Delivered targets must not remain selected for retry');
assert.equal(writableFallback,false,'Forum without verified topics exposes writable main destination');
assert.equal(overflow.clipped.length,0,'Composer controls are clipped on mobile');
